### ISSUE TITLE
Not working as intended.

### ISSUE THREAD

**Issue by Noname12345GER** [Noname12345GER/SSD_Extention_Keypad#1]
Time to ask @MattJeanes and @willox about it.

You probably ask why I have mentioned both of you here. Well,

I was trying to make a Sonic Screwdriver Extention with would enable users to control Keypads with are quite common in DarkRP. I've tried adding 1 and 1 together but, nothing happened.

My question would be, is Process(True) addressed correctly, or is the syntax on the Screwdriver not right?

**Comment by AmyJeanes** [comment]
Use `true` not `True` and `false` not `False`, all lua keywords are lower-case

**Comment by Noname12345GER** [comment]
im feeling stupid now.

**Comment by Noname12345GER** [comment]
would you consider adding it matt ?
